version: "3"

services:
  carros-postgres:
    image: postgres
    environment:
      POSTGRES_DB: "carros"
      POSTGRES_PASSWORD: "admin"
      PGDATA: /var/lib/postgresql/data/psql
    ports:
      - "15432:5432"
    volumes:
      - /Users/crys/dev/docker/postgresql:/var/lib/postgresql/data
    networks:
      - carros-postgres-network

  email-pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "funcionario@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "16543:80"
    depends_on:
      - carros-postgres
    networks:
      - carros-postgres-network

networks:
  carros-postgres-network:
    driver: bridge